name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/wakatime-readme-stat/ 
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        env:
          WAKAPI_API_KEY: ${{ secrets.WAKAPI_API_KEY }}
          WAKAPI_URL: ${{ secrets.WAKAPI_URL }}
          WAKAPI_USER: ${{ secrets.WAKAPI_USER }}
